version: '3.9'

services:

  db:
    container_name: sms_emulator-mysql57
    image: mysql:5.7
    restart: always
    ports:
      - 3310:3306
    environment:
       MYSQL_ROOT_PASSWORD: lmd
       MYSQL_DATABASE: sms_emulator
       MYSQL_USER: sms_emulator
       MYSQL_PASSWORD: lmd
    stdin_open: true
    tty: true

  sms_emulator:
    container_name: sms_emulator-main
    depends_on:
      - db
    image: python:3.7-slim-buster
    restart: always
    links:
      - db
    ports:
      - 9000:8000
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3310
      MYSQL_ROOT_PASSWORD: lmd
      MYSQL_DATABASE: sms_emulator
      MYSQL_USER: sms_emulator
      MYSQL_PASSWORD: lmd
    volumes:
      - ../../sms_emulator:/sms_emulator
    working_dir: /sms_emulator
    command:  bash -c "apt-get update && apt-get install python3-dev default-libmysqlclient-dev gcc -y && pip3 install --no-cache-dir -r requirements.txt && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true